DATASET:
  VAL: "coco_2014_online_val"
  TEST: "coco_2014_online_test"
MODEL:
  DECODER:
    CORE: "ConvHiddenCore"
    ATTENTION: "DualAttention"
    BEAM_SIZE: 3
  WEIGHT: 'save/model.pth'
  DEVICE: 'cpu'
