DATASET:
  TRAIN: "coco_2014_train_simple"
  VAL: "coco_2014_val_simple"
  TEST: "coco_2014_test_simple"
SOLVER:
  BASE_LR: 0.01
  STEPS: (30, 50)
  MAX_ITER: 100
  WARMUP_ITERS: 10
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 1
  VAL_PERIOD: 10
  SCST_AFTER: 0
  IMS_PER_BATCH: 8
MODEL:
  DECODER:
    BEAM_SIZE: 3
    CORE: "ConvHiddenCore"
    ATTENTION: "DualAttention"
  WEIGHT: "save/model.pth"
